---
- name: fetch, process, and upload cve to s3
  hosts: localhost
  gather_facts: false
  vars_files: vars.yaml
  tasks:
  - name: run python script to fetch, process, and upload cve dataset to s3
    command: python3 ./scripts/fetch_upload_cve.py
    environment:
      AWS_REGION: "{{ defaultregion }}"
      S3_BUCKET_NAME: "{{ bucket_name }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
  tags: fetch_cve

- name: setup glue database
  hosts: localhost
  gather_facts: false
  vars_files: vars.yaml
  tasks:
  - name: create glue database
    command: >
      aws glue create-database
      --database-input '{"Name": "{{ glue_database_name }}", "Description": "Glue database for CVE vulnerability data lake."}'
  - name: run python script to create glue table and athena workgroup
    command: python3 ./scripts/gluetable_athena.py
    environment:
      AWS_REGION: "{{ defaultregion }}"
      S3_BUCKET_NAME: "{{ bucket_name }}"
      GLUE_DATABASE_NAME: "{{ glue_database_name }}"
      GLUE_TABLE_NAME: "{{ glue_table_name }}"
      ATHENA_OUTPUT_LOCATION: "s3://{{ bucket_name }}/athena-results/"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
  tags: gluetable_athena

