---
- name: fetch, process, and upload cve to s3
  hosts: localhost
  gather_facts: false
  vars_files: vars.yaml
  tasks:
  - name: run python script to fetch, process, and upload cve dataset to s3
    command: python3 ./scripts/fetch_upload_cve.py
    environment:
      AWS_REGION: "{{ defaultregion }}"
      S3_BUCKET_NAME: "{{ bucket_name }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"

  tags: fetch_cve

