---
- name: Generate Athena query reports and publish to SNS
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: Define query strings
      set_fact:
        athena_output_location: "s3://{{ bucket_name }}/athena-results/"
        queries:
          - name: "Top Critical Vulnerabilities"
            query: >
              SELECT cve_id, description, cvss_v3_base_score, cvss_v3_base_severity, published_date
              FROM {{ glue_database_name }}.{{ glue_table_name }}
              WHERE cvss_v3_base_score >= 9.0
              ORDER BY cvss_v3_base_score DESC
              LIMIT 10;
          - name: "Most Recent Vulnerabilities"
            query: >
              SELECT cve_id, description, cvss_v3_base_score, published_date
              FROM {{ glue_database_name }}.{{ glue_table_name }}
              WHERE published_date >= DATE('2024-01-01')
              ORDER BY published_date DESC
              LIMIT 10;
          - name: "Vendor-Specific Vulnerabilities"
            query: >
              SELECT cve_id, vendor, product, description, cvss_v3_base_score
              FROM {{ glue_database_name }}.{{ glue_table_name }}
              WHERE vendor = 'Microsoft'
              ORDER BY cvss_v3_base_score DESC
              LIMIT 10;

    - name: Run Athena queries and save results to S3
      shell: >
        aws athena start-query-execution
        --query-string "{{ item.query }}"
        --query-execution-context Database={{ glue_database_name }}
        --result-configuration "OutputLocation={{ athena_output_location }}/reports/"
      register: query_results
      with_items: "{{ queries }}"
      loop_control:
        label: "{{ item.name }}"
      tags: athena_queries

    - name: Wait for query completion
      shell: >
        aws athena get-query-execution
        --query-execution-id "{{ item.QueryExecutionId }}"
        --query "QueryExecution.Status.State"
      register: query_status
      until: query_status.stdout == "SUCCEEDED"
      retries: 10
      delay: 5
      with_items: "{{ query_results.results }}"
      loop_control:
        label: "{{ item.name }}"
      tags: athena_queries

    - name: Download query results from S3
      shell: >
        aws s3 cp "{{ athena_output_location }}/reports/{{ item.QueryExecutionId }}.csv" ./reports/{{ item.name | replace(' ', '_') }}.csv
      with_items: "{{ query_results.results }}"
      loop_control:
        label: "{{ item.name }}"
      tags: s3_download

    - name: Publish reports to SNS topic
      shell: >
        aws sns publish
        --topic-arn "{{ sns_arn }}"
        --subject "{{ item.name }}"
        --message "The query report for '{{ item.name }}' is attached. Please download it from: {{ athena_output_location }}/reports/{{ item.QueryExecutionId }}.csv"
      with_items: "{{ query_results.results }}"
      loop_control:
        label: "{{ item.name }}"
      tags: sns_publish

